version: '3'

services:

  pg_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: commonUser
      POSTGRES_PASSWORD: SECRET_PASSWORD
    ports:
      - "5432:5432"