spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: commonUser
    password: SECRET_PASSWORD
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
          fetch_size: 30