spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 60
          fetch_size: 60